def main():
    print("=" * 70)
    print("🚀 MCP Server with Google Gemini API")
    print("=" * 70)
    print("\n📦 Project Components:")
    print("\n   🧮 Math Server - Arithmetic operations")
    print("   🌤️ Weather Server - Real-time weather data")
    print("   🤖 AI Agent - Google Gemini powered orchestrator")
    print("\n" + "=" * 70)
    print("📋 Available Commands:")
    print("=" * 70)
    print("\n1. Install dependencies:")
    print("   pip install --break-system-packages -r requirements.txt")
    print("\n2. Set your Google Gemini API key:")
    print("   export GOOGLE_API_KEY='your_api_key_here'")
    print("\n3. Start Math Server (Terminal 1):")
    print("   python3 mathserver.py")
    print("\n4. Start Weather Server (Terminal 2):")
    print("   python3 weather.py")
    print("\n5. Run MCP Client (Terminal 3):")
    print("   python3 client.py")
    print("\n" + "=" * 70)
    print("🔑 API Key Setup:")
    print("=" * 70)
    print("\nTo set your API key, run:")
    print("   export GOOGLE_API_KEY='your_google_api_key_here'")
    print("\n" + "=" * 70)
    print("💡 Full Quick Start (Copy & Paste):")
    print("=" * 70)
    print("\n# Install dependencies")
    print("pip install --break-system-packages -r requirements.txt")
    print("\n# Set API key")
    print("export GOOGLE_API_KEY='your_google_api_key_here'")
    print("\n# Terminal 1 - Math Server")
    print("python3 mathserver.py")
    print("\n# Terminal 2 - Weather Server")
    print("python3 weather.py")
    print("\n# Terminal 3 - Run Client")
    print("python3 client.py")
    print("\n" + "=" * 70)
    print("✅ Hello from MCP Server with Google Gemini!")
    print("=" * 70 + "\n")

if __name__ == "__main__":
    main()
